ignoredBuiltDependencies:
  - msw

onlyBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - node-pty
  - protobufjs
  - sharp
  - supabase
  - tree-sitter-bash
  - unrs-resolver

overrides:
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  next@>=16.0.0-beta.0 <16.0.9: '>=16.0.9'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  prismjs@<1.30.0: '>=1.30.0'
