
import { db } from "@/lib/db/drizzle";
import { users } from "@/lib/db/schema";
import { createPTESession, getUserPTESessions } from "@/lib/db/queries/pte-sessions";
import { eq } from "drizzle-orm";

async function verifyUserSession() {
    console.log("Starting user session verification...");

    // 1. Get or Create a Test User
    const testEmail = "test-verification-user@example.com";

    // Try to find existing user first to avoid unique constraint violation if insert fails race condition (unlikely in script but good practice)
    let user = await db.query.users.findFirst({
        where: eq(users.email, testEmail),
    });

    if (!user) {
        console.log(`User ${testEmail} not found. Creating...`);
        try {
            const [newUser] = await db.insert(users).values({
                email: testEmail,
                name: "Test verification User",
                role: "user",
                emailVerified: false,
                id: crypto.randomUUID(), // Ensure ID is generated if not auto-generated by DB default
            }).returning();
            user = newUser;
        } catch (e) {
            // Handle race condition or re-fetch if insert failed
            console.log("Insert failed, trying to fetch again...", e);
            user = await db.query.users.findFirst({
                where: eq(users.email, testEmail),
            });
        }
    }

    if (!user) {
        console.error("❌ CRTICAL FAILURE: Could not get or create user.");
        process.exit(1);
    }

    console.log(`Using user: ${user.email} (ID: ${user.id})`);

    // 2. Create a PTE Session
    console.log("Creating PTE session...");
    const session = await createPTESession(user.id);
    console.log(`Session created: ${session.id}`);

    // 3. Verify Session Retrieval
    console.log("Retrieving user sessions...");
    const userSessions = await getUserPTESessions(user.id);

    const found = userSessions.find(s => s.id === session.id);

    if (found) {
        console.log("✅ SUCCESS: Session found in user history.");
        console.log(`- Session ID: ${found.id}`);
        console.log(`- Created At: ${found.createdAt}`);
        console.log(`- Status: ${found.isCompleted ? 'Completed' : 'In Progress'}`);
    } else {
        console.error("❌ FAILURE: Created session NOT found in user history.");
        console.log("Fetched sessions IDs:", userSessions.map(s => s.id));
        process.exit(1);
    }
}

verifyUserSession().catch((e) => {
    console.error("Script execution failed:", e);
    process.exit(1);
}).finally(() => {
    console.log("Verification checks completed.");
    process.exit(0);
});
